apiVersion: v1
kind: Secret
metadata:
  name: devpulse-secrets
  labels:
    app: devpulse
type: Opaque
stringData:
  JIRA_API_TOKEN: "REPLACE_ME"
  JWT_SECRET_KEY: "REPLACE_ME"
  GITHUB_TOKEN: "REPLACE_ME"
