apiVersion: v1
kind: ServiceAccount
metadata:
  name: devpulse
  labels:
    app: devpulse
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.devpulse: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"devpulse"}}'
