apiVersion: v1
kind: Service
metadata:
  name: devpulse
  labels:
    app: devpulse
spec:
  selector:
    app: devpulse
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
