apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devpulse-dev

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml

configMapGenerator:
  - name: devpulse-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
